from __future__ import annotations

import json
from datetime import date

from fastapi.testclient import TestClient

from obsidian_srs_agent.app import web
from obsidian_srs_agent.app.agent import PipelinePreview
from obsidian_srs_agent.app.models import Card, CardGenControls, SourceDoc, WriteResult


class DummyAgent:
    def __init__(self, tmp_path):
        self.tmp_path = tmp_path

    def generate(self, config):  # pragma: no cover - exercised via test client
        preview = PipelinePreview(
            cards=[
                Card(front="What is SRS?", back="Spaced repetition system.", style="basic"),
            ],
            source=SourceDoc(text="SRS stands for spaced repetition system.", title="Test", url="http://example.com"),
            controls=CardGenControls(num_cards=1),
            model="gpt-4o-mini",
            prompt_tokens=100,
            completion_tokens=50,
        )
        return preview

    def write(self, preview, config):
        path = self.tmp_path / "Decks" / "test" / "topic" / "deck.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("Question::Answer\n", encoding="utf-8")
        return WriteResult(path=str(path), created=date.today(), deck_tag="#deck/test/topic")


def test_web_preview_and_confirm_flow(tmp_path, monkeypatch):
    client = TestClient(web.app)
    dummy = DummyAgent(tmp_path)
    monkeypatch.setattr(web, "_agent", dummy)

    base_payload = {
        "vault_path": str(tmp_path),
        "domain": "Test",
        "topic": "Topic",
        "raw_text": "SRS info",
        "num_cards": "1",
    }

    response = client.post("/process", data=base_payload)
    assert response.status_code == 200
    assert "Preview 1 cards" in response.text
    assert "Generated by gpt-4o-mini" in response.text

    cards_payload = json.dumps(
        [
            {
                "front": "What is SRS?",
                "back": "Spaced repetition system.",
                "style": "basic",
                "difficulty": "medium",
                "tags": [],
            }
        ]
    )

    confirm_payload = {
        **base_payload,
        "confirm": "yes",
        "cards_payload": cards_payload,
        "source_title_hidden": "Test",
        "source_url_hidden": "http://example.com",
    }

    confirm_response = client.post("/process", data=confirm_payload)
    assert confirm_response.status_code == 200
    assert "Wrote cards" in confirm_response.text
    assert "Written cards" in confirm_response.text
