"""Agent job orchestration."""

from __future__ import annotations

import asyncio
from dataclasses import dataclass

from .baml_integration import DocAuthoringService
from .github_client import GitHubAPI
from .models import AgentJobPayload, AgentJobResult
from .repo_intel import RepoIntelBuilder


@dataclass(slots=True)
class AgentContext:
    repo: str
    pr_number: int
    head_ref: str
    head_sha: str
    base_ref: str
    files: list[dict]


class AgentRunner:
    """Coordinates GitHub interactions with documentation generation."""

    def __init__(self, authoring_service: DocAuthoringService) -> None:
        self._authoring_service = authoring_service

    async def gather_context(self, github: GitHubAPI, job: AgentJobPayload) -> AgentContext:
        pr = await github.get_pull_request(job.repository, job.pr_number)
        files = await github.get_pull_request_files(job.repository, job.pr_number)
        return AgentContext(
            repo=job.repository,
            pr_number=job.pr_number,
            head_ref=pr["head"]["ref"],
            head_sha=pr["head"]["sha"],
            base_ref=pr["base"]["ref"],
            files=files,
        )

    async def run(self, github: GitHubAPI, job: AgentJobPayload) -> AgentJobResult:
        context = await self.gather_context(github, job)
        intel = RepoIntelBuilder(context.repo, context.pr_number, context.files).build()
        payload = RepoIntelBuilder.payload_for_mode(job.mode, intel, job.notes)
        patches = await asyncio.to_thread(
            self._authoring_service.generate_patches, job.mode, payload
        )
        if not patches:
            return AgentJobResult(branch="", companion_pr_url=None, changed_files=[])
        branch = job.branch_name(context.head_ref)
        await github.ensure_branch(context.repo, branch, context.head_sha)
        await github.upsert_files(
            context.repo,
            branch,
            message=f"auto-docs: {job.mode.value}",
            files=((patch.path.as_posix(), patch.content) for patch in patches),
        )
        body_lines = [
            "## What changed",
            *[f"- {patch.path.as_posix()}" for patch in patches],
            "",
            "## Why",
            "- Generated by the auto-docs bot.",
            "",
            f"Linked to #{context.pr_number}",
        ]
        pr = await github.create_pull_request(
            context.repo,
            head=branch,
            base=context.base_ref,
            title=f"[auto-docs] {job.mode.value} for #{context.pr_number}",
            body="\n".join(body_lines),
        )
        return AgentJobResult(
            branch=branch,
            companion_pr_url=pr.get("html_url"),
            changed_files=[patch.path for patch in patches],
        )


__all__ = ["AgentContext", "AgentRunner"]
