"""Agent strategy abstractions for documentation generation."""

from __future__ import annotations

import asyncio
import json
import os
import subprocess
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

from .commands import DocsMode
from .models import DocPatch, validate_patches


def _summarise_files(
    repo: str, pr_number: int, files: Iterable[dict[str, Any]]
) -> dict[str, Any]:
    doc_files: list[str] = []
    code_files: list[str] = []
    diff_snippets: list[str] = []
    findings: list[str] = []

    for file in files:
        filename = str(file.get("filename", ""))
        status = str(file.get("status", "modified"))
        patch = file.get("patch")

        if filename.endswith((".md", ".mdx")):
            doc_files.append(filename)
        else:
            code_files.append(filename)

        if patch:
            header = f"[{filename} - {status}]"
            diff_snippets.append(f"{header}\n{patch}")

        if status == "renamed":
            findings.append(
                f"{filename} was renamed; ensure docs reference the new name."
            )

    if not findings:
        if code_files:
            findings.append(
                "Review related documentation for the updated code paths: "
                + ", ".join(code_files)
            )
        else:
            findings.append(
                "No code files changed; perform a general documentation sweep."
            )

    repo_hint_lines = [
        f"Repository: {repo}",
        f"Pull Request: #{pr_number}",
        f"Code files touched ({len(code_files)}): {', '.join(code_files) or 'none'}",
        f"Doc files touched ({len(doc_files)}): {', '.join(doc_files) or 'none'}",
    ]

    return {
        "repo_hints": "\n".join(repo_hint_lines),
        "diff_snippets": diff_snippets,
        "findings": findings,
    }


def _payload_for_mode(
    mode: DocsMode, insights: dict[str, Any], notes: str
) -> dict[str, Any]:
    payload = {"notes": notes}
    if mode is DocsMode.QUICKSTART:
        return {**payload, "repo_hints": insights["repo_hints"]}
    if mode is DocsMode.UPDATE:
        snippets = insights["diff_snippets"] or [insights["repo_hints"]]
        return {**payload, "diff_snippets": snippets}
    findings = (
        insights["findings"] or insights["diff_snippets"] or [insights["repo_hints"]]
    )
    return {**payload, "findings": findings}


@dataclass(slots=True)
class AgentContext:
    """Contextual information passed to agent strategies."""

    repo: str
    pr_number: int
    head_ref: str
    head_sha: str
    base_ref: str
    files: list[dict[str, Any]]
    mode: DocsMode
    notes: str


@dataclass(slots=True)
class AgentArtifacts:
    """Artifacts returned by a strategy after analysing the repository."""

    patches: list[DocPatch]
    pr_title: str
    pr_body: str
    commit_message: str | None = None


class AgentStrategy(Protocol):
    """Protocol for agent strategies capable of producing documentation updates."""

    async def generate(
        self, context: AgentContext
    ) -> AgentArtifacts:  # pragma: no cover - interface
        ...


@dataclass(slots=True)
class ClaudeCodeAgentStrategy:
    """Agent strategy powered by the Claude Code tooling and BAML prompts."""

    authoring_service: Any

    async def generate(self, context: AgentContext) -> AgentArtifacts:
        insights = _summarise_files(context.repo, context.pr_number, context.files)
        payload = _payload_for_mode(context.mode, insights, context.notes)
        patches = await asyncio.to_thread(
            self.authoring_service.generate_patches, context.mode, payload
        )
        patches = validate_patches(patches)
        pr_title = f"[auto-docs] {context.mode.value} for #{context.pr_number}"
        changes = [f"- {patch.path.as_posix()}" for patch in patches]
        if not changes:
            changes = ["- No documentation updates"]
        body_lines = [
            "## What changed",
            *changes,
            "",
            "## Why",
            "- Generated by the auto-docs bot.",
            "",
            f"Linked to #{context.pr_number}",
        ]
        return AgentArtifacts(
            patches=patches,
            pr_title=pr_title,
            pr_body="\n".join(body_lines),
            commit_message=f"auto-docs: {context.mode.value}",
        )


@dataclass(slots=True)
class CodexCliAgentStrategy:
    """Agent strategy that shells out to a Codex CLI in headless mode."""

    executable: str = "codex"
    extra_env: Mapping[str, str] | None = None
    runner: Callable[[dict[str, Any]], str] | None = None

    async def generate(self, context: AgentContext) -> AgentArtifacts:
        payload = {
            "repo": context.repo,
            "pr_number": context.pr_number,
            "mode": context.mode.value,
            "notes": context.notes,
            "files": context.files,
        }
        runner = self.runner or self._run_cli
        output = await asyncio.to_thread(runner, payload)
        data = json.loads(output)
        patches = [
            DocPatch(
                path=Path(item["path"]),
                content=item["content"],
                rationale=item.get("rationale"),
            )
            for item in data.get("patches", [])
        ]
        patches = validate_patches(patches)
        pr_title = data.get(
            "pr_title",
            f"[auto-docs] {context.mode.value} for #{context.pr_number}",
        )
        pr_body = data.get(
            "pr_body",
            "Generated by Codex CLI agent.",
        )
        return AgentArtifacts(
            patches=patches,
            pr_title=pr_title,
            pr_body=pr_body,
            commit_message=data.get("commit_message"),
        )

    def _run_cli(self, payload: dict[str, Any]) -> str:
        env = None
        if self.extra_env:
            env = {**os.environ, **dict(self.extra_env)}
        try:
            completed = subprocess.run(  # noqa: S603 subprocess-used
                [self.executable, "docs-agent"],
                input=json.dumps(payload),
                text=True,
                check=True,
                capture_output=True,
                env=env,
            )
        except FileNotFoundError as exc:  # pragma: no cover - runtime validation
            raise RuntimeError(
                f"Codex CLI executable '{self.executable}' not found"
            ) from exc
        except (
            subprocess.CalledProcessError
        ) as exc:  # pragma: no cover - runtime validation
            raise RuntimeError(
                f"Codex CLI failed with exit code {exc.returncode}: {exc.stderr}"
            ) from exc
        return completed.stdout


__all__ = [
    "AgentArtifacts",
    "AgentContext",
    "AgentStrategy",
    "ClaudeCodeAgentStrategy",
    "CodexCliAgentStrategy",
]
