"""Agent job orchestration."""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass

from .agent_strategies import AgentStrategy
from .github_client import GitHubAPI
from .models import AgentJobPayload, AgentJobResult, DocPatch
from .repo_intel import RepoIntelBuilder


@dataclass(slots=True)
class AgentContext:
    repo: str
    pr_number: int
    head_ref: str
    head_sha: str
    base_ref: str
    files: list[dict]


class AgentRunner:
    """Coordinates GitHub interactions with documentation generation."""

    def __init__(self, strategy: AgentStrategy) -> None:
        self._strategy = strategy

    async def gather_context(self, github: GitHubAPI, job: AgentJobPayload) -> AgentContext:
        pr = await github.get_pull_request(job.repository, job.pr_number)
        files = await github.get_pull_request_files(job.repository, job.pr_number)
        return AgentContext(
            repo=job.repository,
            pr_number=job.pr_number,
            head_ref=pr["head"]["ref"],
            head_sha=pr["head"]["sha"],
            base_ref=pr["base"]["ref"],
            files=files,
        )

    async def run(self, github: GitHubAPI, job: AgentJobPayload) -> AgentJobResult:
        context = await self.gather_context(github, job)
        insights = RepoIntelBuilder(context.repo, context.pr_number, context.files).build()
        agent_output = await self._strategy.generate(job, context, insights)
        if not agent_output.patches:
            return AgentJobResult(branch="", companion_pr_url=None, changed_files=[])
        branch = job.branch_name(context.head_ref)
        await github.ensure_branch(context.repo, branch, context.head_sha)
        await github.upsert_files(
            context.repo,
            branch,
            message=agent_output.commit_message or f"auto-docs: {job.mode.value}",
            files=_iter_patch_contents(agent_output.patches),
        )
        pr = await github.create_pull_request(
            context.repo,
            head=branch,
            base=context.base_ref,
            title=agent_output.pr_title
            or f"[auto-docs] {job.mode.value} for #{context.pr_number}",
            body=agent_output.pr_body or _default_pr_body(context.pr_number, agent_output.patches),
        )
        return AgentJobResult(
            branch=branch,
            companion_pr_url=pr.get("html_url"),
            changed_files=[patch.path for patch in agent_output.patches],
        )


def _iter_patch_contents(patches: Iterable[DocPatch]):
    for patch in patches:
        yield patch.path.as_posix(), patch.content


def _default_pr_body(pr_number: int, patches: Iterable[DocPatch]) -> str:
    lines = ["## What changed"]
    for patch in patches:
        lines.append(f"- {patch.path.as_posix()}")
    lines.extend(
        [
            "",
            "## Why",
            "- Generated by the auto-docs bot.",
            "",
            f"Linked to #{pr_number}",
        ]
    )
    return "\n".join(lines)


__all__ = ["AgentContext", "AgentRunner"]
